### PR TITLE
The updated UI for BlocklyDuino

### PR DESCRIPTION
**Pull request by azyth**
This UI mimics the layout of the Codebender site and is much more pleasing to the eye then the current layout.

### CODE REVIEW

**Comment by spiliot** [comment]
@codebendercc/cornell  I'm bringing the attention of all the team on this so I won't need to write it down multiple times.

# A note about commit messages

Taking the last commit here as an example, `Lookin' sooooooo goooood` is funny, and I hate fun. **In fact I hate fun so much that I'll have to delete the whole branch for you to redo**. 

Well no, don't worry, that was meant to be funny in its own, my point is that there's nothing wrong with being witty or funny as long as the commit message _is helpful_.

In this case noone can guess what changed. In one month (or even in a week) you won't be able to remember yourself what you did in that commit, let alone in a year. You, or anyone else will need to open it and have a look inside to understand what changed, which is a waste of time.

That being said, don't make it so generic either to get it over with like "changed index.php". Thank you, I could find that out in 1 click, but now I have to figure out what changed and why. If you can't figure out a good message then it's probably because of pushing early which is summed up next.

So, commit messages should be something that sums up the committed changes in such a way that if one looks at it in the future, will be able to understand what changed. The commit message is **part** of the code you commit so give it at least enough thought as your code (which assumes you gave enough thought in your code in the first place, right? :grin: ).

# Pushing early

We asked you to push early in order to be able to review the changes and let you know if we feel something is veering off course (we do the same here as part of our daily routine). That means that there are times when you will have to commit progress in several commits.

The way to deal with that is that once you're finished, you squash the changes to one commit that makes sense. For example, if you decide to fix forgotten whitespace in 30 files and that is done over 10 commits, once you finish you should squash them all together in one commit (`git rebase`) and add a helpful commit  message like "Removed whitespace from project files". Not only this is easier to review, it helps if in the future one needs to find where something changed (know `git blame`?).

If you remember I told you on Skype that branching with git comes cheap and should be used. So fixing whitespace could be done on its own branch and be pushed/merged as one commit in the end. You could therefor open a pull request for just that (for us to review changes if needed) label it "hold" (so we know it is work on progress that shouldn't be merged yet) and when done with it remove hold and add "for review".

**Comment by kyleoliveira** [comment]
Sorry about that, I meant to squash/rebase tsome of the work on that branch before putting it up, but it was at the end of the hack-a-thon and I forgot. I'll try to be more explicit I the future ;)

**Comment by spiliot** [comment]
No worries Kyle, it was a good chance to say this for everybody.

**Comment by spiliot** [comment]
@codebendercc/cornell  Guys, Fotis is still sick and we don't have your skype name to call, can you send it here or to spiliot@codebender.cc? Thanks.

**Comment by spiliot** [comment]
Is work on this branch finished?

**Comment by kyleoliveira** [comment]
I believe it should be. Right @azyth ?

**Comment by azyth** [comment]
Yes all of this work is complete.

**Comment by spiliot** [comment]
Alright, as far code is concerned it's :+1: 

What I'd like to see is all of the above commits squashed to one or two. In fact I was kind of expecting this to be already done once the ready for review flag was set but perhaps I wasn't so clear about that before.

Let's do it and I'll be merging it in afterwards!

**Comment by spiliot** [comment]
Closed as code is merged in #10

**Pull request closed without merging**
