### PR TITLE
Server quickstart

### PR DESCRIPTION
**Pull request by kyleoliveira**
Should give you everything you need to get our BlocklyDuino implementation set up in an Ubuntu VM.

I'm opening this Pull Request with my work so far - I haven't tested it out on a fresh VM yet.

### CODE REVIEW

**Comment by kyleoliveira** [comment]
Works on my VM. @azyth if you could verify locally, I think we'll be ready to give it a run on AWS.

**Comment by azyth** [comment]
Testing it on a brand new local install of Ubuntu server in a VM it works. (many issues with the test but they were all related to virtual box and not the script.) once virtual box was finally configured properly was able to drop the script in by sshing in via a terminal. the script ran fine, it did produce a nginx user not found error at the end but that does not effect the end result as far as i can tell. I did not copy the other two files along with startup.sh which may eleviate that error. restarting the server and accessing the ip in a browser produces the old blockly page.

**Comment by tzikis** [comment]
Sounds good to me. If no one objects, let's test it on AWS ;)

**Comment by kyleoliveira** [comment]
I'm not getting any error regarding the nginx user when I run the file.

You can avoid copy-and-pasting it by running

```
wget https://raw.githubusercontent.com/codebendercc/BlocklyDuino/server_quickstart/server_quickstart/quickstart.sh
```

from within the VM.

**Comment by azyth** [comment]
nginx error was due to a username issue. all sorted out.

**Pull request merged**
