### PR TITLE
PHPUnit test working pull request

### PR DESCRIPTION
**Pull request by azyth**
unit tests for blocklyduino.

### CODE REVIEW

**Comment by azyth** [comment]
I will go back through and redo my outline of tests, sorry for the confusion

**Comment by spiliot** [comment]
I think there are some misconceptions hiding here so let's try to get one step back...

A unit test is a kind of white box testing where you're only interested in the reaction of the "unit" in **isolation** via a mocked environment. Anything out of the class the function belongs in should be mocked so the function interacts only with a controlled environment. In this context we should be testing the actual function that i.e. creates a random password. Does it return the number of characters it is supposed to? If you run it 5 times will it produce different passwords? Do they contain at least a number? If you run it with a null argument will it fail gracefully? That kind of questions.

A functional (integration) test, is a kind of black box testing where you test the reaction of a particular set of functions all together describing a high end functionality of the system. For example, if I call "/get/235?sort=asc" will I get the database contents the fixture with number 235 contains sorted? If I call "/delete/235" without being logged in will I get an error response?

An acceptance or automation test is a very high level test that is actually looking to the application from the perspective of the final user. For example, if a user clicks on the login button with valid credentials will she be logged and shown a page that contains a div with a welcome message? Will on that page be an element to logout? Or in our case, "will the list of boards populate?".

What we asked were Unit and Functional tests (and since your code is quite simple, probably more of the second). You seem to be trying to do automation testing with the tools for unit/functional testing and that's why you stumble, it's not that the tools aren't adequate, they are simply not designed for that!

**Comment by kyleoliveira** [comment]
Thank you for spelling that all out, it is helpful to know what you guys expect. 

I think my only disagreement would be in your definitions of "functional" and "automation" tests. Everything I've seen in the past has referred to anything that isn't done by a human as an "automated" test. I've mainly seen "functional" tests referred to as something between what you're describing as an integration test and an acceptance test, namely tests that cover interactions between multiple units/subsystems that define some sort of function of the system as a whole (typically represented as a use case or user story). 

Further, I would argue that testing that the boards list populates is not an acceptance test - it's testing that our override of compilerflasher's functionality works (i.e. the interface between the two units is correct) and that's an integration test. An acceptance test of that area of functionality would be to test that, after selecting a board and clicking the verify code button a proper response is returned to the user.

All that said and given what you've laid out there, _what actual unit tests can we make?_ We have one that tests that the Blockly iframe actually loads. (woo!) Nearly everything else is delivered by somebody else (blockly or compilerflasher), so it seems more appropriate to write some integration tests. That's really what John was trying to go for here, according to your definitions.

So, unless you have something else on the page that we can make a unit test for, let's say John is going to write some integration tests. _What would you expect us to write integration tests for?_ By your definition, it seems like we'd only write a few that check that the JavaScript/CSS/etc. assets are available. By my definition, I'd think we'd at least write that one to test our compilerflasher override as well.

As you know, nearly everything in this app runs through JavaScript. Unless I'm mistaken, we need a web driver like Selenium if we're going to interact with JavaScript. That's why John was asking if we should write a variation on the Silex\WebTestCase that extends PHPUnit_Extensions_Selenium2TestCase instead of PHPUnit_Extensions_TestCase. The PHPUnit manual indicates that that is the class to extend if you'd like to use Selenium in your tests (https://phpunit.de/manual/current/en/selenium.html), it _should_ be easy to do, and it's something we can contribute back to Silex.

However, we already have that capability baked into Behat, which is what I'm using for the functional/acceptance tests that I'm writing, so if you really think that simply testing that, for example, compilerflasher is filling dropdowns correctly is something that must be written as an acceptance test, we can go about it that way. Please just confirm that that is the plan and we'll move ahead accordingly.

**Comment by spiliot** [comment]
Let's not dive into the fine details of each term on comments, I'll be sending you an email in a while :)

**Comment by azyth** [comment]
This is not the branch i was talking about.

**Pull request closed without merging**
